### ISSUE TITLE
[Feature]: Update icalevents to 0.2.0 to work with Home Assistant 2025.1

### ISSUE THREAD

**Issue by stefan1495** [mampfes/hacs_waste_collection_schedule#3648]
### I propose a feature for:

The integration in general

### Describe your wanted feature

icalevents got updated to 0.2.0 (https://github.com/jazzband/icalevents/releases/tag/v0.2.0) and is now compatible with icalender v6. Waste Collection Schedule should use that Version to make ics-sources work again with Home Assistant 2025.1.

**Comment by fsedarkalex** [comment]
this would be great

**Comment by THorst92** [comment]
Unfortunately I am not aware how to do a pull request, but the following workaround is working for me:
change line 12 in file "manifest.json" to:
`"icalevents>=0.2.0",`
and restart Home Assistant

**Comment by fsedarkalex** [comment]
> Unfortunately I am not aware how to do a pull request, but the following workaround is working for me: change line 12 in file "manifest.json" to: `"icalevents>=0.2.0",` and restart Home Assistant

confirmed

**Comment by jimmybonesde** [comment]
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:226
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 12:32:41 (2 Vorkommnisse)
Zuletzt protokolliert: 12:32:41

error loading source karlsruhe_de: cannot import name 'use_pytz' from 'icalendar' (/usr/local/lib/python3.13/site-packages/icalendar/__init__.py) Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 217, in create source_module: SourceModule = importlib.import_module( ~~~~~~~~~~~~~~~~~~~~~~~^ f"waste_collection_schedule.source.{source_name}" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module return _bootstrap._gcd_import(name[level:], package, level) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 1026, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/karlsruhe_de.py", line 6, in <module> from waste_collection_schedule.service.ICS import ICS File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 7, in <module> from icalevents import icalevents File "/usr/local/lib/python3.13/site-packages/icalevents/icalevents.py", line 3, in <module> from .icalparser import parse_events, Event File "/usr/local/lib/python3.13/site-packages/icalevents/icalparser.py", line 18, in <module> from icalendar import use_pytz ImportError: cannot import name 'use_pytz' from 'icalendar' (/usr/local/lib/python3.13/site-packages/icalendar/__init__.py)
error loading source ics: cannot import name 'use_pytz' from 'icalendar' (/usr/local/lib/python3.13/site-packages/icalendar/__init__.py) Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 217, in create source_module: SourceModule = importlib.import_module( ~~~~~~~~~~~~~~~~~~~~~~~^ f"waste_collection_schedule.source.{source_name}" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module return _bootstrap._gcd_import(name[level:], package, level) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 1026, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 15, in <module> from waste_collection_schedule.service.ICS import ICS File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 7, in <module> from icalevents import icalevents File "/usr/local/lib/python3.13/site-packages/icalevents/icalevents.py", line 3, in <module> from .icalparser import parse_events, Event File "/usr/local/lib/python3.13/site-packages/icalevents/icalparser.py", line 18, in <module> from icalendar import use_pytz ImportError: cannot import name 'use_pytz' from 'icalendar' (/usr/local/lib/python3.13/site-packages/icalendar/__init__.py)

**Comment by stefan1495** [comment]
> Dieser Fehler stammt von einer benutzerdefinierten Integration
> 
> Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:226 Integration: Waste Collection Schedule (Dokumentation) Erstmals aufgetreten: 12:32:41 (2 Vorkommnisse) Zuletzt protokolliert: 12:32:41
> 
> error loading source karlsruhe_de: cannot import name 'use_pytz' from 'icalendar' (/usr/local/lib/python3.13/site-packages/icalendar/**init**.py) Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 217, in create source_module: SourceModule = importlib.import_module( ~~~~~~~~~~~~~~~~~~~~~~~^ f"waste_collection_schedule.source.{source_name}" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.13/importlib/**init**.py", line 88, in import_module return _bootstrap._gcd_import(name[level:], package, level) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1387, in _gcd_import File "", line 1360, in _find_and_load File "", line 1331, in _find_and_load_unlocked File "", line 935, in _load_unlocked File "", line 1026, in exec_module File "", line 488, in _call_with_frames_removed File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/karlsruhe_de.py", line 6, in from waste_collection_schedule.service.ICS import ICS File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 7, in from icalevents import icalevents File "/usr/local/lib/python3.13/site-packages/icalevents/icalevents.py", line 3, in from .icalparser import parse_events, Event File "/usr/local/lib/python3.13/site-packages/icalevents/icalparser.py", line 18, in from icalendar import use_pytz ImportError: cannot import name 'use_pytz' from 'icalendar' (/usr/local/lib/python3.13/site-packages/icalendar/**init**.py) error loading source ics: cannot import name 'use_pytz' from 'icalendar' (/usr/local/lib/python3.13/site-packages/icalendar/**init**.py) Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 217, in create source_module: SourceModule = importlib.import_module( ~~~~~~~~~~~~~~~~~~~~~~~^ f"waste_collection_schedule.source.{source_name}" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.13/importlib/**init**.py", line 88, in import_module return _bootstrap._gcd_import(name[level:], package, level) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1387, in _gcd_import File "", line 1360, in _find_and_load File "", line 1331, in _find_and_load_unlocked File "", line 935, in _load_unlocked File "", line 1026, in exec_module File "", line 488, in _call_with_frames_removed File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 15, in from waste_collection_schedule.service.ICS import ICS File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 7, in from icalevents import icalevents File "/usr/local/lib/python3.13/site-packages/icalevents/icalevents.py", line 3, in from .icalparser import parse_events, Event File "/usr/local/lib/python3.13/site-packages/icalevents/icalparser.py", line 18, in from icalendar import use_pytz ImportError: cannot import name 'use_pytz' from 'icalendar' (/usr/local/lib/python3.13/site-packages/icalendar/**init**.py)

Did you revert those other "fixes" that are around here? Your Manifest should look like this:

 `"requirements": [ "icalendar", "icalevents==0.2.0", "beautifulsoup4", "lxml", "pycryptodome" ],`
