### ISSUE TITLE
Problems with HA 2022.2.1 / 2022.2.2?

### ISSUE THREAD

**Issue by H4rl3k1n** [mampfes/hacs_waste_collection_schedule#164]
Hi, since HA 2022.2.1 my waste dates wont come up anymore, it worked well with 2022.2.0 and older versions. Errormessage:
`fetch failed for source <waste_collection_schedule.source.ics.Source object at 0x7f89189190>: 'NoneType' object has no attribute 'upper'`
I havent changed anything with the source-file, just updated HA to latest version.
Please have a look at this, thanks in advance.

**Comment by JimmyGiant** [comment]
Hey, I have the same issue. In my case since the end of december 2021 the integration keeps breaking and then suddenly working again after some time. I had no trouble whatsoever in the twelve months before and I have not changed anything besides the updates. My local waste-service is not yet integrated so I am using a link to the .ics file. Since 2022.2.1 it stopped working again. Hope it helps, thanks!

**Comment by bairnhard** [comment]
Same problem here.
My quick fix: I created a google calendar, imported the ics there, and use the google calendar iCal URL in HA. That solved it for now.

**Comment by mampfes** [comment]
Please share your config and ics file. I'm not able to reproduce it so far.

**Comment by H4rl3k1n** [comment]
Hey, thanks for checking this issue.

Heres my config:

sensors.yaml
`# Müllkalender
- platform: waste_collection_schedule
  name: AbfallRestmuell
  details_format: upcoming
  value_template: '{{value.date}}'
  types:
    - Restmüll in Forstern

- platform: waste_collection_schedule
  name: AbfallBio
  details_format: upcoming
  value_template: '{{value.date}}'
  types:
    - Biotonne in Forstern

- platform: waste_collection_schedule
  name: AbfallPapier
  details_format: upcoming
  value_template: '{{value.date}}'
  types:
    - Papiertonne in Forstern

- platform: waste_collection_schedule
  name: AbfallgelberSack
  details_format: upcoming
  value_template: '{{value.date}}'
  types:
    - Gelber Sack in Forstern`

configuration.yaml
`#Abfallkalender
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/abfuhrkalender/Abfuhrkalender-Forstern-2022.ics"
      customize:
        - type: Restmüll in Forstern
          show: true
          icon: mdi:trash-can
        - type: Biotonne in Forstern
          show: true
          icon: mdi:trash-can
        - type: Papiertonne in Forstern
          show: true
          icon: mdi:trash-can
        - type: Gelber Sack in Forstern
          show: true
          icon: mdi:recycle
      calendar_title: CALENDAR_TITLE
  fetch_time: "04:00"
  day_switch_time: "07:00"`

I cant upload the ics file cause github doesnt allow it, but heres the link:
[https://www.landkreis-erding.de/abfallwirtschaft/rund-um-die-entsorgung/abfuhrkalender-interaktiv/](url)
City "Forstern", use any street you like, all the same file.

PS: i just updated to 2022.2.2 and used a fresh ics-file, still the same error.

**Comment by saschaabraham** [comment]
Same error here. Used an ICS file  from my provider.

**Comment by bairnhard** [comment]
Here's my config, that works.
the local file produced the same error as described above, but after uploading it to a google calendar, and reading it from there it just works. If you have a google account you can add as many calendars as you like, and you can even make them invisible so they don't interfere with whatever else you do with your Google account. 

`
# Abfall Kalender
waste_collection_schedule:
  sources:
    - name: ics
      args:
#        file: "Abfuhrkalender-Germering-2022.ics"
        url: "https://calendar.google.com/calendar/ical/lalilu-verrat-ich-nicht%40group.calendar.google.com/private-trallala-auch-geheim/basic.ics"
        offset: 0
      customize: 
        - type: Papiertonne
          alias: papiermuell
          icon: mdi:trash-can
        - type: Restmuelltonne
          alias: restmuell
          icon: mdi:trash-can
        - type: Wertstofftonne
          alias: wertstoffmuell
          icon: mdi:recycle
  fetch_time: "04:00"
  day_switch_time: "11:00"`

**Comment by H4rl3k1n** [comment]
thanks @bairnhard, worked for me too. local file still not working, ics via google calendar works.

**Comment by fogowitz** [comment]
Same Problem as H4rl3k1n same ics file "Landkreis" Erding.
Is there a solution beside the workarround with the google calendar?

**Comment by mampfes** [comment]
I create prerelease 1.16.0-pre2 which tries to address this issue. It uses a different python package to parse ICS data. Could s.o. test this please?
Note: You have to enable the switch "Show beta versions" in HACS to be able to see this pre-release.

**Comment by s--p** [comment]
> I create prerelease 1.16.0-pre2 which tries to address this issue. It uses a different python package to parse ICS data. Could s.o. test this please? Note: You have to enable the switch "Show beta versions" in HACS to be able to see this pre-release.

Just tried the 1.16.0-pre2 and for me it's working again. 
Thanks a lot!

**Comment by H4rl3k1n** [comment]
Hi, just tested your beta, it now works again with local file. Many thanks!

**Comment by tschnilo** [comment]
I also tried the 1.16.0-pre2. And it works for me again too..
Thx!

**Comment by fogowitz** [comment]
Works well again, thank you so much!

 
 

Gesendet: Samstag, 12. Februar 2022 um 11:17 Uhr
Von: "Steffen Zimmermann" ***@***.***>
An: "mampfes/hacs_waste_collection_schedule" ***@***.***>
Cc: "fogowitz" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [mampfes/hacs_waste_collection_schedule] Problems with HA 2022.2.1 / 2022.2.2? (Issue #164)


 

I create prerelease 1.16.0-pre2 which tries to address this issue. It uses a different python package to parse ICS data. Could s.o. test this please?
Note: You have to enable the switch "Show beta versions" in HACS to be able to see this pre-release.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mampfes** [comment]
Fixed in release 1.16.0

**Comment by fogowitz** [comment]
Works well, thank you
