### ISSUE TITLE
After Update to 1.21.0 waste_collection_schedule is unable to load

### ISSUE THREAD

**Issue by robbi-git** [mampfes/hacs_waste_collection_schedule#261]
After Update to 1.21.0 waste_collection_schedule is unable to load.
Before the update the waste_collection_schedule ran without any probs.

Error: 
Unable to prepare setup for platform waste_collection_schedule.calendar: Platform not found (cannot import name 'CalendarEntity' from 'homeassistant.components.calendar' (/usr/src/homeassistant/homeassistant/components/calendar/__init__.py)).

Reload the Repo via HACS and restart does no solve the Prob.

HA core-2022.4.4, OS 8.1

Is there already a solution or an idea what I can do ?

Many thanks
Rob

**Comment by mampfes** [comment]
Please update to HA 2022-5.

**Comment by robbi-git** [comment]
After Update to HA 2022.6.7 waste_collection_schedule works as expected again.
Thanks
Rob
