### ISSUE TITLE
[Source Defect]: Germany; AHE; Ennepetal

### ISSUE THREAD

**Issue by Koxxi89** [mampfes/hacs_waste_collection_schedule#6773]
### Source Name

Ennepetal

### What's happening?

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.waste_collection_schedule
Quelle: config_entries.py:798
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 10:36:35 (6 Vorkommnisse)
Zuletzt protokolliert: 22:11:59

Error setting up entry AHE Ennepe-Ruhr-Kreis for waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/init_ui.py", line 56, in async_setup_entry
    shell = await hass.async_add_executor_job(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 282, in create
    source: Fetchable = source_module.Source(**source_args)  # type: ignore
                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: Source.__init__() got an unexpected keyword argument 'plz'


### Error Logs

```Shell
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.waste_collection_schedule
Quelle: config_entries.py:798
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 10:36:35 (6 Vorkommnisse)
Zuletzt protokolliert: 22:11:59

Error setting up entry AHE Ennepe-Ruhr-Kreis for waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/init_ui.py", line 56, in async_setup_entry
    shell = await hass.async_add_executor_job(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 282, in create
    source: Fetchable = source_module.Source(**source_args)  # type: ignore
                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: Source.__init__() got an unexpected keyword argument 'plz'
```

### Source Configuration

```YAML
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.waste_collection_schedule
Quelle: config_entries.py:798
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 10:36:35 (6 Vorkommnisse)
Zuletzt protokolliert: 22:11:59

Error setting up entry AHE Ennepe-Ruhr-Kreis for waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/init_ui.py", line 56, in async_setup_entry
    shell = await hass.async_add_executor_job(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 282, in create
    source: Fetchable = source_module.Source(**source_args)  # type: ignore
                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: Source.__init__() got an unexpected keyword argument 'plz'
```

### Checklist

- [x] I have tested with the latest version (master branch) via HACS → 3-dot menu → Redownload → select `master`
- [x] The service provider's website is still working
- [x] I have tested with the example parameters from the documentation
- [x] I have searched past issues (open and closed) for this problem

**Comment by LoganFanGer** [comment]
I have exactly the same Problems. No entrys. No Data in Calender. Dont work after Update to 26.7.1

**Comment by JoniRousu** [comment]
Hatte das Problem auch. / Also had that problem.
Habe es durch Neukonfiguration der Quelle gelöst, da PLZ durch Stadt abgelöst wurde, siehe [Übersicht auf Github](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ahe_de.md#how-to-get-the-source-argument). / I solved it by reconfiguring the source, because plz was replaced by city name, see [overview on Github](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ahe_de.md#how-to-get-the-source-argument).

**Comment by bbr111** [comment]
You must read the release notes:

fixed ahe_de: rebuilt on abfallplus platform after atino.net shutdown; breaking change: plz parameter replaced by city (https://github.com/mampfes/hacs_waste_collection_schedule/pull/6741)
