### ISSUE TITLE
[Bug]: "Config flow could not be loaded" after update to 2.6.0

### ISSUE THREAD

**Issue by martinflux** [mampfes/hacs_waste_collection_schedule#3511]
### I Have A Problem With:

The integration in general

### What's Your Problem

Hi,

first of all thanks for this great project and your efforts! Since a couple of days I experience instability in the sense that my waste calendar was sporadically unavailable as the loading of the source was unreliable (see Logs section II.). Since update to 2.6.0 this morning, I experience an additional challenge which is that I can no longer access the configuration.

Clicking on "Configure" results in the below error message (see also logs part I.):

![image](https://github.com/user-attachments/assets/03d884b9-3747-4de8-8684-f8cb0e457822)

Thanks in advance for your advice on how to resolve this!

Regards,
Martin

### Source (if relevant)

muellmax_de / Abfallwirtschaftsbetriebe Münster

### Logs

```Shell
##################################
# I. Configuration / Setup issue #
##################################

Logger: homeassistant.components.calendar
Source: helpers/entity_platform.py:366
integration: Calendar (documentation, issues)
First occurred: 08:36:56 (1 occurrences)
Last logged: 08:36:56

Error while setting up waste_collection_schedule platform for calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/waste_collection_schedule/calendar.py", line 165, in async_setup_entry
    entities = create_calendar_entries([shell], coordinator=coordinator)
  File "/config/custom_components/waste_collection_schedule/calendar.py", line 129, in create_calendar_entries
    dedicated_calendar_types = shell.get_dedicated_calendar_types()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_dedicated_calendar_types'



############################
# II. Source Loading issue #
############################

This error originated from a custom integration.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:226
integration: Waste Collection Schedule (documentation)
First occurred: 08:36:54 (1 occurrences)
Last logged: 08:36:54

error loading source muellmax_de: No module named 'icalendar.windows_to_olson' Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 217, in create source_module: SourceModule = importlib.import_module( ~~~~~~~~~~~~~~~~~~~~~~~^ f"waste_collection_schedule.source.{source_name}" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module return _bootstrap._gcd_import(name[level:], package, level) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 1026, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/muellmax_de.py", line 5, in <module> from waste_collection_schedule.service.ICS import ICS File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 7, in <module> from icalevents import icalevents File "/usr/local/lib/python3.13/site-packages/icalevents/icalevents.py", line 3, in <module> from .icalparser import parse_events, Event File "/usr/local/lib/python3.13/site-packages/icalevents/icalparser.py", line 18, in <module> from icalendar.windows_to_olson import WINDOWS_TO_OLSON ModuleNotFoundError: No module named 'icalendar.windows_to_olson'
```

### Relevant Configuration

```YAML
I have set up one sensor by waste type using value template  {{value.daysTo}} which worked out ok so far.
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Nemor213** [comment]
Same here

**Comment by markvp** [comment]
Thanks for the detailed report, @martinflux!

The error at the heart of this is:

> `ModuleNotFoundError: No module named 'icalendar.windows_to_olson'`

This is the same root cause as #3489 and #3445 — a newer version of the `icalendar` library removed the `windows_to_olson` submodule that an older version of `icalevents` depended on. The cascade (`'NoneType' object has no attribute 'get_dedicated_calendar_types'`) is a side-effect of the source module failing to load.

This has been fixed in PR #6486, which bumps the minimum `icalevents` version to `>=0.2.1`. The fix is included in the latest master. Updating the integration (HACS → three-dot menu → Redownload → choose master) should resolve it.

Closing as a duplicate of that fix — please reopen if you're still seeing this on the latest version.
